POST http://localhost:3000/api/user
Content-Type: application/json

{
    "userId": "IF123456",
    "username": "test",
    "firstname": "test",
    "lastname": "test",
    "email": "test@test.at",
    "clazz": "5BHITM",
    "birthdate": "2002-05-08",
    "biografie": "test",
    "permissions": 1,
    "department": "Informatik"
}

###

GET http://localhost:3000/api/user?userId=IF123456

###

PUT http://localhost:3000/api/user
Content-Type: application/json

{
  "userId": "IF123456",
  "username": "test12",
  "firstname": "test",
  "lastname": "test",
  "email": "test@test.at",
  "clazz": "5BHITM",
  "birthdate": "2002-05-08",
  "biografie": "test",
  "permissions": 1,
  "department": "Informatik"
}

###

DELETE http://localhost:3000/api/user?userId=IF123456

###

POST http://localhost:3000/api/userAbility
Content-Type: application/json

{
    "userId": "IF123456",
    "abilityId": 1
}

###

GET http://localhost:3000/api/userAbility?userId=IF123456

###

DELETE http://localhost:3000/api/userAbility?userId=IF123456&abilityId=1

###

POST http://localhost:3000/api/notification
Content-Type: application/json

{
      "userId": "IF123456",
      "title": "test",
      "text": "test"
}

###

GET http://localhost:3000/api/notification?userId=IF123456

###

DELETE http://localhost:3000/api/notification?userId=IF123456&notificationId=2

###

GET http://localhost:3000/api/abilities