apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectmatch
  namespace: student-a-jasic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectmatch
  template:
    metadata:
      labels:
        app: projectmatch
    spec:
      containers:
        - name: projectmatch
          image: docker.io/alinjasic/projectmatch:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
---
apiVersion: v1
kind: Service
metadata:
  name: projectmatch-svc
  namespace: student-a-jasic
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: projectmatch
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projectmatch-ingress
  namespace: student-a-jasic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /a.jasic/projectmatch/(.*)$
            pathType: Prefix
            backend:
              service:
                name: projectmatch-svc
                port:
                  number: 80
