name: "Docker build & push"
#on: Trigger for running the workflow
on:
 push:
    branches: [ main ]
      #define the jobs to run
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          # path to Dockerfile build context
          context: ./src
          push: true
          tags: alinjasic/projectmatch
